let token=localStorage.getItem("lord_admin");const $=id=>document.getElementById(id);const money=n=>new Intl.NumberFormat("ar-SY").format(n)+" ل.س";
function show(){ $("login").classList.add("hidden");$("app").classList.remove("hidden");load()}
async function api(url,opt={}){opt.headers={...(opt.headers||{}),Authorization:"Bearer "+token};let r=await fetch(url,opt);if(r.status===401){localStorage.removeItem("lord_admin");location.reload()}return r}
$("loginBtn").onclick=async()=>{let r=await fetch("/api/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username:$("user").value,password:$("pass").value})});let d=await r.json();if(!r.ok)return $("loginErr").textContent=d.error;token=d.token;localStorage.setItem("lord_admin",token);show()};
$("logout").onclick=()=>{localStorage.removeItem("lord_admin");location.reload()};
async function load(){let r=await api("/api/admin/dashboard"),d=await r.json();$("sProducts").textContent=d.counts.products;$("sActive").textContent=d.counts.activeProducts;$("sOrders").textContent=d.counts.orders;$("sPending").textContent=d.counts.pending;
$("setName").value=d.settings.storeName;$("setPhone").value=d.settings.phone;$("setWa").value=d.settings.whatsapp;$("setFb").value=d.settings.facebook;$("setSham").value=d.settings.shamCashNumber;$("setDelivery").value=d.settings.deliveryNote;
$("productsBody").innerHTML=d.products.map(p=>`<tr><td>${p.image?`<img class="product-thumb" src="${p.image}">`:"—"}</td><td><b>${p.name}</b><br><small>${p.description||""}</small></td><td>${p.cat}</td><td>${money(p.price)}</td><td>${p.stock}</td><td>${p.active?"متاح":"مخفي"}</td><td><button class="mini" onclick="editProduct(${p.id})">تعديل</button> <button class="mini danger" onclick="deleteProduct(${p.id})">حذف</button></td></tr>`).join("");
$("ordersBody").innerHTML=d.orders.length?d.orders.map(o=>`<tr><td>${o.id}<br><small>${new Date(o.createdAt).toLocaleString("ar-SY")}</small></td><td><b>${o.customer.name}</b><br>${o.customer.phone}<br>${o.customer.city} — ${o.customer.address}</td><td>${o.items.map(i=>`${i.name} × ${i.qty}`).join("<br>")}</td><td>${money(o.total)}</td><td>${o.payment}</td><td><select class="mini" onchange="statusOrder('${o.id}',this.value)">${["جديد","قيد التجهيز","تم الشحن","مكتمل","ملغى"].map(s=>`<option ${o.status===s?"selected":""}>${s}</option>`).join("")}</select></td></tr>`).join(""):"<tr><td colspan=6>لا توجد طلبات بعد.</td></tr>"}
$("newProduct").onclick=()=>openEditor();
}
function openEditor(p={}){$("productEditor").classList.remove("hidden");$("productEditor").innerHTML=`<div class="panel" style="margin-top:15px"><h3>${p.id?"تعديل المنتج":"إضافة منتج"}</h3><div class="admin-form"><label>اسم المنتج<input id="pn" value="${p.name||""}"></label><label>الفئة<select id="pc"><option>سيارات</option><option>دراجات</option><option>إكسسوارات</option></select></label><label>السعر<input id="pp" type="number" value="${p.price||0}"></label><label>المخزون<input id="ps" type="number" value="${p.stock||0}"></label><label class="wide">الوصف<textarea id="pd">${p.description||""}</textarea></label><label class="wide">صورة المنتج<input id="pi" type="file" accept="image/*"></label></div><button class="primary-btn" onclick="saveProduct(${p.id||0})">حفظ</button> <button class="ghost-btn" onclick="$('productEditor').classList.add('hidden')">إلغاء</button></div>`;if(p.cat)$("pc").value=p.cat}
async function editProduct(id){let r=await api("/api/admin/dashboard"),d=await r.json();openEditor(d.products.find(p=>p.id===id))}
async function saveProduct(id){let image="";let file=$("pi").files[0];if(file){let f=new FormData();f.append("image",file);let r=await api("/api/admin/upload",{method:"POST",body:f});let d=await r.json();image=d.url}let body={name:$("pn").value,cat:$("pc").value,price:Number($("pp").value),stock:Number($("ps").value),description:$("pd").value};if(image)body.image=image;let r=await api(id?"/api/admin/products/"+id:"/api/admin/products",{method:id?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok)return alert((await r.json()).error);$("productEditor").classList.add("hidden");load()}
async function deleteProduct(id){if(!confirm("حذف المنتج؟"))return;await api("/api/admin/products/"+id,{method:"DELETE"});load()}
async function statusOrder(id,status){await api("/api/admin/orders/"+id,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});load()}
$("saveSettings").onclick=async()=>{let body={storeName:$("setName").value,phone:$("setPhone").value,whatsapp:$("setWa").value,facebook:$("setFb").value,shamCashNumber:$("setSham").value,deliveryNote:$("setDelivery").value};await api("/api/admin/settings",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});alert("تم حفظ الإعدادات");load()};
if(token)show();
